= {page-component-title}

Using https://hop.apache.org[Apache Hop^] to process IATI data.

The code processes IATI XML data to produce content in a Postgres database.
The data is put into a dimensional model 
to allow different analytics platforms 
to present the data in dashboards and reports.

The code uses a spreadsheet with "seed activities" as a starting point.
It currently assumes a two-tier approach,
with _programme_ activities on the top level,
and _project_ activities on the bottom level.

The same spreadsheet is also used to define IATI result indicators to show.
In addition, it contains a mapping table for disaggregated data.
These tables help standardise the presentation of data.

== History

This project started as a project based on Pentaho Data Integration (PDI).

In 2005, Kettle started as open source ETL tool, with a visual programming interface.
It turned into Pentaho Data Integration.

In 2019, the original authors created a fork to allow experimentation to develop it further.
The project was brought under the stewardship of the Apache Foundation, and named Hop.

To benefit from the more rigourous licensing,
as well as the huge upgrade in software setup,
we migrated our PDI code to Hop.

Apache Hop code can be run on a local machine,
and also be deployed to cloud services via Apache Beam.

== Setup

* First, we need to xref:setup/azure.adoc[set up Azure].
* Next, we xref:setup/database.adoc[prepare the database].
 